### ISSUE TITLE
Issueのオープンとクローズの違い

### ISSUE THREAD

**Issue by seiya-Unity** [seiya-Unity/game#1]
質問1
オープンとクローズがあるんですけど、どんな違いがあるんですか？
質問2
また、この会話は他の人にも見られるんですか？
質問3
また、ポートフォリオとして提出する際はどのようにして企業に渡すんですか？

**Comment by inaba-human-unity** [comment]
- 質問1
Issueは本来、問題点を書き込むのに使います。
その為、オープンは未解決。クローズは解決済みとして使用するのが一般的ですね。

- 質問2
Publicなので、これは見れちゃいますね。

- 質問3
上記の通り誰でも見れてるので、GitHubアカウント見せてもいいですし
作品の画像や動画見せてもいいかもですね！
